### ISSUE TITLE
the config.yaml in the project is not a valid one

### ISSUE THREAD

**Issue by reduxdj** [apollographql/supergraph-demo-fed2#302]
the config.yaml in the project is not a valid one
 
```
server:
  listen: 0.0.0.0:5002
  graphql_path: /graphql
cors:
  # Set to true to allow any origin
  # (Defaults to false)
  allow_any_origin: true
  # origins:
  #   - http://localhost
  #   - https://studio.apollographql.com # Keep this so Apollo Studio can run queries against your router
  # match_origins:
  #   - "https://([a-z0-9]+[.])*api[.]example[.]com" # any host that uses https and ends with .api.example.com
```
